spring.datasource.url=jdbc:mysql://sietestore-db-jc3403591-069b.e.aivencloud.com:23803/siete_store_db?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_wahCjdX4XjOSDShhgt0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Usar dialecto estándar de Hibernate para MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update